### ISSUE TITLE
wgdi -conf ./conf.ini error

### ISSUE THREAD

**Issue by Hua-CM** [SunPengChuan/wgdi#11]
It encounter the error bellow:
~~~python
Traceback (most recent call last):
  File "/home/anaconda3/bin/wgdi", line 8, in <module>
    sys.exit(main())
  File "/home/anaconda3/lib/python3.7/site-packages/wgdi/run.py", line 146, in main
    module_to_run(arg, value)
  File "/home/anaconda3/lib/python3.7/site-packages/wgdi/run.py", line 107, in module_to_run
    program, conf, name = tuple(switcher.get(argument))
~~~

I have modified the row 107 in run.py and fix the problem:
~~~python
if argument == 'configure':
    run_configure()
else:
    program, conf, name = tuple(switcher.get(argument))
    run_subprogram(program, conf, name)
~~~

**Comment by SunPengChuan** [comment]
Thank you very much, I forgot to test it here. I will modify it immediately.

**Comment by SunPengChuan** [comment]
done.
