### ISSUE TITLE
wgdi can not recognize the PATH of mafft

### ISSUE THREAD

**Issue by tinyfallen** [SunPengChuan/wgdi#21]
Dear developer,

I  met the following issue using wgdi to calculate the ks and need some help. Looking forward to your reply, thanks!

cds_file  =  tsin.cds
pep_file  =  tsin.prot
align_software  =  muscle
pairs_file  =  icl.txt
ks_file  =  ks.txt
Traceback (most recent call last):
  File "/export/home/ydn/.conda/envs/cg/bin/wgdi", line 8, in <module>
    sys.exit(main())
  File "/export/home/ydn/.conda/envs/cg/lib/python3.9/site-packages/wgdi/run.py", line 158, in main
    module_to_run(arg, value)
  File "/export/home/ydn/.conda/envs/cg/lib/python3.9/site-packages/wgdi/run.py", line 118, in module_to_run
    run_subprogram(program, conf, name)
  File "/export/home/ydn/.conda/envs/cg/lib/python3.9/site-packages/wgdi/run.py", line 84, in run_subprogram
    r.run()
  File "/export/home/ydn/.conda/envs/cg/lib/python3.9/site-packages/wgdi/ks.py", line 101, in run
    kaks = self.pair_kaks(k)
  File "/export/home/ydn/.conda/envs/cg/lib/python3.9/site-packages/wgdi/ks.py", line 113, in pair_kaks
    self.align()
  File "/export/home/ydn/.conda/envs/cg/lib/python3.9/site-packages/wgdi/ks.py", line 134, in align
    stdout, stderr = muscle_cline()
  File "/export/home/ydn/.conda/envs/cg/lib/python3.9/site-packages/Bio/Application/__init__.py", line 574, in __call__
    raise ApplicationError(return_code, str(self), stdout_str, stderr_str)
**Bio.Application.ApplicationError: Non-zero return code 127 from 'C:\\bio\\muscle3.8.31_i86win32.exe -in pair.pep -out prot.aln -seqtype protein -clwstrict', message '/bin/sh: C:biomuscle3.8.31_i86win32.exe: command not found'**

Traceback (most recent call last):
  File "/export/home/ydn/.conda/envs/cg/bin/wgdi", line 8, in <module>
    sys.exit(main())
  File "/export/home/ydn/.conda/envs/cg/lib/python3.9/site-packages/wgdi/run.py", line 158, in main
    module_to_run(arg, value)
  File "/export/home/ydn/.conda/envs/cg/lib/python3.9/site-packages/wgdi/run.py", line 118, in module_to_run
    run_subprogram(program, conf, name)
  File "/export/home/ydn/.conda/envs/cg/lib/python3.9/site-packages/wgdi/run.py", line 84, in run_subprogram
    r.run()
  File "/export/home/ydn/.conda/envs/cg/lib/python3.9/site-packages/wgdi/ks.py", line 101, in run
    kaks = self.pair_kaks(k)
  File "/export/home/ydn/.conda/envs/cg/lib/python3.9/site-packages/wgdi/ks.py", line 113, in pair_kaks
    self.align()
  File "/export/home/ydn/.conda/envs/cg/lib/python3.9/site-packages/wgdi/ks.py", line 128, in align
    stdout, stderr = mafft_cline()
  File "/export/home/ydn/.conda/envs/cg/lib/python3.9/site-packages/Bio/Application/__init__.py", line 574, in __call__
    raise ApplicationError(return_code, str(self), stdout_str, stderr_str)
**Bio.Application.ApplicationError: Non-zero return code 127 from 'C:\\bio\\mafft-win\\mafft.bat --auto pair.pep', message '/bin/sh: C:biomafft-winmafft.bat: command not found'**

**Comment by tinyfallen** [comment]
Sorry for disturbing, I found the description at [https://wgdi.readthedocs.io/en/latest/Installation.html]
