### ISSUE TITLE
Error in Dotplot stage

### ISSUE THREAD

**Issue by ardy20** [SunPengChuan/wgdi#25]
Hello SunPeng

I started Wgdi but after running wgdi -d total.conf I get the following error:

 wgdi -d total.conf
blast  =  /scratch/project_mnt/S0030/wgdi/male-female/blast_results/male_blast
gff1  =  /scratch/project_mnt/S0030/wgdi/male-female/male-v1.0.a4.62d0dba6b61fa-publish.genes.gff3
gff2  =  /scratch/project_mnt/S0030/wgdi/male-female/male-v1.0.a4.62d0dba6b61fa-publish.genes.gff3
lens1  =  /scratch/project_mnt/S0030/wgdi/male-female/jojoba_male.lens
lens2  =  /scratch/project_mnt/S0030/wgdi/male-female/jojoba_male.lens
genome1_name  =  jojoba male
genome2_name  =  jojoba male
multiple  =  1
score  =  100
evalue  =  1e-5
repeat_number  =  10
position  =  order
blast_reverse  =  false
ancestor_left  =  none
ancestor_top  =  none
markersize  =  0.5
figsize  =  10,10
savefig  =  male_Jojoba(.png, .pdf, .svg)
Traceback (most recent call last):
  File "/scratch/project/qaafi-cnafs/wgdi/bin/wgdi", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/scratch/project/qaafi-cnafs/wgdi/lib/python3.11/site-packages/wgdi/run.py", line 158, in main
    module_to_run(arg, value)
  File "/scratch/project/qaafi-cnafs/wgdi/lib/python3.11/site-packages/wgdi/run.py", line 118, in module_to_run
    run_subprogram(program, conf, name)
  File "/scratch/project/qaafi-cnafs/wgdi/lib/python3.11/site-packages/wgdi/run.py", line 84, in run_subprogram
    r.run()
  File "/scratch/project/qaafi-cnafs/wgdi/lib/python3.11/site-packages/wgdi/dotplot.py", line 96, in run
    gff1 = base.newgff(self.gff1)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/project/qaafi-cnafs/wgdi/lib/python3.11/site-packages/wgdi/base.py", line 177, in newgff
    gff['start'] = gff['start'].astype(np.int64)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/project/qaafi-cnafs/wgdi/lib/python3.11/site-packages/pandas/core/generic.py", line 6240, in astype
    new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/project/qaafi-cnafs/wgdi/lib/python3.11/site-packages/pandas/core/internals/managers.py", line 450, in astype
    return self.apply("astype", dtype=dtype, copy=copy, errors=errors)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/project/qaafi-cnafs/wgdi/lib/python3.11/site-packages/pandas/core/internals/managers.py", line 352, in apply
    applied = getattr(b, f)(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/project/qaafi-cnafs/wgdi/lib/python3.11/site-packages/pandas/core/internals/blocks.py", line 526, in astype
    new_values = astype_array_safe(values, dtype, copy=copy, errors=errors)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/project/qaafi-cnafs/wgdi/lib/python3.11/site-packages/pandas/core/dtypes/astype.py", line 299, in astype_array_safe
    new_values = astype_array(values, dtype, copy=copy)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/project/qaafi-cnafs/wgdi/lib/python3.11/site-packages/pandas/core/dtypes/astype.py", line 230, in astype_array
    values = astype_nansafe(values, dtype, copy=copy)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/project/qaafi-cnafs/wgdi/lib/python3.11/site-packages/pandas/core/dtypes/astype.py", line 170, in astype_nansafe
    return arr.astype(dtype, copy=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'gene'

**Comment by SunPengChuan** [comment]
Can you upload screenshots of gff and blast?

**Comment by ardy20** [comment]
Hello Yes

![blast file](https://user-images.githubusercontent.com/63028911/208444247-114165d5-5362-4a77-90f6-104994393f4d.JPG)
![gff3 file](https://user-images.githubusercontent.com/63028911/208444366-480bf5bd-4f12-4c88-986e-5352ccb93f23.JPG)

**Comment by SunPengChuan** [comment]
gff file is not right. you should use the mark.gff not gff3.
https://github.com/SunPengChuan/wgdi/issues/24

**Comment by SunPengChuan** [comment]
yes

**Comment by SunPengChuan** [comment]
Do you want to change the font size?

**Comment by ardy20** [comment]
Yes. For Chr, Is it possible?

**Comment by SunPengChuan** [comment]
It's simple, remove the ‘Chr’ in the first column in the gff and lens files

**Comment by ardy20** [comment]
Does it change the font size? I need to reduce the font size not the word "chr".

**Comment by SunPengChuan** [comment]
It is possible but requires to change the program code. I do not advise you to do this. I often adjust figures with AI.

**Comment by ardy20** [comment]
OK, But what is AI? Artificial Intelligence or it is a program?

Anyway, By any chance Have you seen this? I think it uses Wgdi: 
https://github.com/Emma6674/PolyReco2022/blob/main/PolyReco

**Comment by SunPengChuan** [comment]
AI means Adobe illustrator. I also feel that he learned my code.
