### ISSUE TITLE
_tkinter.TclError: unknown color name "white" I don't know how to solve this error 

### ISSUE THREAD

**Issue by Jiangjiangzhang6** [SunPengChuan/wgdi#32]
Traceback (most recent call last):
  File "/public/home/zhaoli/software/anaconda3/envs/wgdi/bin/wgdi", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/public/home/zhaoli/software/anaconda3/envs/wgdi/lib/python3.11/site-packages/wgdi/run.py", line 158, in main
    module_to_run(arg, value)
  File "/public/home/zhaoli/software/anaconda3/envs/wgdi/lib/python3.11/site-packages/wgdi/run.py", line 118, in module_to_run
    run_subprogram(program, conf, name)
  File "/public/home/zhaoli/software/anaconda3/envs/wgdi/lib/python3.11/site-packages/wgdi/run.py", line 84, in run_subprogram
    r.run()
  File "/public/home/zhaoli/software/anaconda3/envs/wgdi/lib/python3.11/site-packages/wgdi/block_ks.py", line 71, in run
    fig, ax = plt.subplots(figsize=self.figsize)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/public/home/zhaoli/software/anaconda3/envs/wgdi/lib/python3.11/site-packages/matplotlib/pyplot.py", line 1432, in subplots
    fig = figure(**fig_kw)
          ^^^^^^^^^^^^^^^^
  File "/public/home/zhaoli/software/anaconda3/envs/wgdi/lib/python3.11/site-packages/matplotlib/_api/deprecation.py", line 454, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/public/home/zhaoli/software/anaconda3/envs/wgdi/lib/python3.11/site-packages/matplotlib/pyplot.py", line 773, in figure
    manager = new_figure_manager(
              ^^^^^^^^^^^^^^^^^^^
  File "/public/home/zhaoli/software/anaconda3/envs/wgdi/lib/python3.11/site-packages/matplotlib/pyplot.py", line 349, in new_figure_manager
    return _get_backend_mod().new_figure_manager(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/public/home/zhaoli/software/anaconda3/envs/wgdi/lib/python3.11/site-packages/matplotlib/backend_bases.py", line 3505, in new_figure_manager
    return cls.new_figure_manager_given_figure(num, fig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/public/home/zhaoli/software/anaconda3/envs/wgdi/lib/python3.11/site-packages/matplotlib/backend_bases.py", line 3510, in new_figure_manager_given_figure
    return cls.FigureCanvas.new_manager(figure, num)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/public/home/zhaoli/software/anaconda3/envs/wgdi/lib/python3.11/site-packages/matplotlib/backend_bases.py", line 1703, in new_manager
    return cls.manager_class.create_with_canvas(cls, figure, num)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/public/home/zhaoli/software/anaconda3/envs/wgdi/lib/python3.11/site-packages/matplotlib/backends/_backend_tk.py", line 482, in create_with_canvas
    canvas = canvas_class(figure, master=window)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/public/home/zhaoli/software/anaconda3/envs/wgdi/lib/python3.11/site-packages/matplotlib/backends/_backend_tk.py", line 173, in __init__
    self._tkcanvas = tk.Canvas(
                     ^^^^^^^^^^
  File "/public/home/zhaoli/software/anaconda3/envs/wgdi/lib/python3.11/tkinter/__init__.py", line 2744, in __init__
    Widget.__init__(self, master, 'canvas', cnf, kw)
  File "/public/home/zhaoli/software/anaconda3/envs/wgdi/lib/python3.11/tkinter/__init__.py", line 2628, in __init__
    self.tk.call(
_tkinter.TclError: unknown color name "white"

**Comment by Jiangjiangzhang6** [comment]
hello , I run the wgdi software ,it show the error ,the bug informations is like the this. could you help me to debug ??
thank you

**Comment by SunPengChuan** [comment]
Please show the conf file. I’ll take a look and see where the problem is.

**Comment by Jiangjiangzhang6** [comment]
its ok,, I had resolved ,the yesterday night 毕桂萁 ask the question is for me .
thank you 


| |
张江江
|
|
***@***.***
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 5/5/2023 18:22 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [SunPengChuan/wgdi] _tkinter.TclError: unknown color name "white" I don't know how to solve this error (Issue #32) |

Please show the conf file. I’ll take a look and see where the problem is.
