### ISSUE TITLE
Getting problem at karyotype mapping step

### ISSUE THREAD

**Issue by mamtamasand** [SunPengChuan/wgdi#34]
Hello Sir
I am using WGDI tool for chromosomal rearrangements, I followed the tutorial given, but I am stucked at karyotype mapping step , I have five eudicot species, I want to get the chromosomal rearrangement for multiple species. I have mapped my plant species with AEK given in example files. Please help me out with this step:
Till now i have permormed the dotplot analysis, followed by collinearity detection with -icl and WGDI with the "-bi" parameter,  and WGDI with the "-c.

For karyotype mapping I am getting this error:
 File "/home/user/genome_hic/lib/python3.10/site-packages/pandas/core/groupby/grouper.py", line 888, in get_grouper
    raise KeyError(gpr)
 

Please suggest.

**Comment by SunPengChuan** [comment]
Can you provide more error messages?

**Comment by mamtamasand** [comment]
Traceback (most recent call last):
  File "/home/user/genome_hic/bin/wgdi", line 10, in <module>
    sys.exit(main())
  File "/home/user/genome_hic/lib/python3.10/site-packages/wgdi/run.py", line 163, in main
    module_to_run(arg, value)
  File "/home/user/genome_hic/lib/python3.10/site-packages/wgdi/run.py", line 122, in module_to_run
    run_subprogram(program, conf, name)
  File "/home/user/genome_hic/lib/python3.10/site-packages/wgdi/run.py", line 87, in run_subprogram
    r.run()
  File "/home/user/genome_hic/lib/python3.10/site-packages/wgdi/karyotype_mapping.py", line 178, in run
    the_other_ancestor_file = self.karyotype_map(data, lens)
  File "/home/user/genome_hic/lib/python3.10/site-packages/wgdi/karyotype_mapping.py", line 80, in karyotype_map
    for chr, group in ancestor.groupby(0):
  File "/home/user/genome_hic/lib/python3.10/site-packages/pandas/core/frame.py", line 8402, in groupby
    return DataFrameGroupBy(
  File "/home/user/genome_hic/lib/python3.10/site-packages/pandas/core/groupby/groupby.py", line 965, in __init__
    grouper, exclusions, obj = get_grouper(
  File "/home/user/genome_hic/lib/python3.10/site-packages/pandas/core/groupby/grouper.py", line 888, in get_grouper
    raise KeyError(gpr)
KeyError: 0

**Comment by SunPengChuan** [comment]
It feels like there is a problem with the_other_ancestor_file.

**Comment by mamtamasand** [comment]
okay 
Thanks for replying 
Can you provide the input format for the _other_ancestor_file.

**Comment by mamtamasand** [comment]
From the tutorial it seems that  _other_ancestor_file is the result file which will be generated after this program completion.

**Comment by SunPengChuan** [comment]
Can you send me your your.conf file?

**Comment by mamtamasand** [comment]
Okay i will send


[karyotype_mapping]
blast = matches.blast
blast_reverse = false
gff1 = Sr_new.gff
gff2 = AEK.gff
score = 50
evalue = 1e-5
repeat_number = 2
ancestor_left = SR_ancestor.txt
ancestor_top = AEK.ancestor.txt
the_other_lens = SR.lens
blockinfo = corros2_SR.csv
blockinfo_reverse = false
limit_length = 2
the_other_ancestor_file =  resulta2_SR

**Comment by SunPengChuan** [comment]
Ancestor_left and ancestor_top should only be required to keep one, therefore, ancestor_left here is not necessary.

**Comment by mamtamasand** [comment]
I have tried with that also then getting this error

 index = [group.sort_values(by=11, ascending=False)[:int(
Traceback (most recent call last):
  File "/home/user/genome_hic/bin/wgdi", line 10, in <module>
    sys.exit(main())
  File "/home/user/genome_hic/lib/python3.10/site-packages/wgdi/run.py", line 163, in main
    module_to_run(arg, value)
  File "/home/user/genome_hic/lib/python3.10/site-packages/wgdi/run.py", line 122, in module_to_run
    run_subprogram(program, conf, name)
  File "/home/user/genome_hic/lib/python3.10/site-packages/wgdi/run.py", line 87, in run_subprogram
    r.run()
  File "/home/user/genome_hic/lib/python3.10/site-packages/wgdi/karyotype_mapping.py", line 178, in run
    the_other_ancestor_file = self.karyotype_map(data, lens)
  File "/home/user/genome_hic/lib/python3.10/site-packages/wgdi/karyotype_mapping.py", line 80, in karyotype_map
    for chr, group in ancestor.groupby(0):
  File "/home/user/genome_hic/lib/python3.10/site-packages/pandas/core/frame.py", line 8402, in groupby
    return DataFrameGroupBy(
  File "/home/user/genome_hic/lib/python3.10/site-packages/pandas/core/groupby/groupby.py", line 965, in __init__
    grouper, exclusions, obj = get_grouper(
  File "/home/user/genome_hic/lib/python3.10/site-packages/pandas/core/groupby/grouper.py", line 888, in get_grouper
    raise KeyError(gpr)
KeyError: 0

**Comment by SunPengChuan** [comment]
Please send me the files involved in the package via email (sunpengchuan@gmail.com) so that I can test them.
