### ISSUE TITLE
issue with deal_gff.py

### ISSUE THREAD

**Issue by B10inform** [SunPengChuan/wgdi#35]
Hi, Its a great tool. I have some issues with wgdi.
I get following error:

/home/wgdi-example/genome/Aquilegia_coerulea/Aquilegia_coerulea/deal_gff.py:24: FutureWarning: The default value of regex will change from True to False in a future version.
  gff[0] = gff[0].str.replace('Chr0?','')
Traceback (most recent call last):
  File "/home/.local/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3080, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 4554, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 4562, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 2

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/wgdi-example/genome/Aquilegia_coerulea/Aquilegia_coerulea/deal_gff.py", line 20, in <module>
    gff = gff[gff[2] == 'CDS']
  File "/home/.local/lib/python3.10/site-packages/pandas/core/frame.py", line 3024, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/.local/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3082, in get_loc
    raise KeyError(key) from err
KeyError: 2

Thanks

**Comment by SunPengChuan** [comment]
I can’t see other information and feel like a column of CDS is missing. Can you upload more information?
