### ISSUE TITLE
ZeroDivisionError: division by zero and ancestor_location 

### ISSUE THREAD

**Issue by sajjadasaf** [SunPengChuan/wgdi#4]
Dear Chuan,
Thank you very much for your help.
I started with example analysis vv1s and followed the instruction but the following tow errors occur in retain and circos steps.
**1**
/Vitis_vinifera$ wgdi -p total.conf
alignment  =  allignment.csv
gff  =  vv1s.gff
lens  =  vv1s.lens
colors  =  red,blue,gree
gap  =  50
retention  =  0.05
diff  =  0.05
remove_delta  =  (true/false)
savefile  =  index.csv

Polyploidy-index between subgenomes are  []
Traceback (most recent call last):
  File "/home/sajjad/anaconda3/envs/wgd/bin/wgdi", line 10, in <module>
    sys.exit(main())
  File "/home/sajjad/anaconda3/envs/wgd/lib/python3.9/site-packages/wgdi/run.py", line 208, in main
    module_to_run(arg)
  File "/home/sajjad/anaconda3/envs/wgd/lib/python3.9/site-packages/wgdi/run.py", line 174, in module_to_run
    return switcher.get(argument)()
  File "/home/sajjad/anaconda3/envs/wgd/lib/python3.9/site-packages/wgdi/run.py", line 131, in run_pindex
    p.run()
  File "/home/sajjad/anaconda3/envs/wgd/lib/python3.9/site-packages/wgdi/pindex.py", line 66, in run
    p = self.cal_pindex(alignment)
  File "/home/sajjad/anaconda3/envs/wgd/lib/python3.9/site-packages/wgdi/pindex.py", line 98, in cal_pindex
    return sum(data)/len(data)
ZeroDivisionError: division by zero

Please help me to resolve this issue.

**2**

TH 2nd query is regarding the final circos map, from where i can get the following files
!) ancestor location 
2) ancestor
3) It also shows that column names attribute  is missing.

**Comment by SunPengChuan** [comment]
Documentation for installation along with a user tutorial, a default parameter file, and test data are provided. 
please consult the docs at http://wgdi.readthedocs.io/en/latest/ and  https://github.com/SunPengChuan/wgdi-example .
here are some videos  in https://www.bilibili.com/video/BV1qK4y1U7eK/  and  https://www.bilibili.com/video/BV195411P7L1/
